---
name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release, windows-release-asan, windows-debug]
        include:
          - os: windows-2022
            triplet: x64-windows
            packages: >
              sccache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "1G"
          variant: "sccache"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Remove Windows pre-installed MySQL
        if: contains( matrix.os, 'windows')
        run: rm -r -fo C:/mysql*

      - name: Restore artifacts and install vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 8b62d95a81afcb9efe74bebeb62f04c1e0e2a003

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: canary-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/
